#!/bin/sh

\. ../../../nvm.sh
nvm install 0.10.7
nvm install 1.0.0
nvm install --lts

if [ -f ".nvmrc" ]; then
  mv .nvmrc .nvmrc.bak
fi

if [ -f ".node-version" ]; then
  mv .node-version .node-version.bak
fi
