#!/bin/sh

cd ../..
mkdir v0.0.1
mkdir src/node-v0.0.1

sudo touch v0.0.1/sudo

. ./nvm.sh

RETURN_MESSAGE="$(nvm uninstall v0.0.1 2>&1)"
CHECK_FOR="Cannot uninstall, incorrect permissions on installation folder"

test "${RETURN_MESSAGE#*$CHECK_FOR}" != "$RETURN_MESSAGE" || exit 1
