#!/usr/bin/env bash

export NVM_SYMLINK_CURRENT=true
. ../../nvm.sh

rm -rf ../../v0.10.29
mkdir ../../v0.10.29
nvm use 0.10.29
rmdir ../../v0.10.29

if [ ! -L ../../current ];then
  echo "Expected 'current' symlink to be created!"
  exit 1
fi

oldLink="$(readlink ../../current)"

if [ "$(basename $oldLink)" != 'v0.10.29' ];then
  echo "Expected 'current' to point to v0.10.29 but was $oldLink"
  exit 1
fi

rm -rf ../../v0.11.13
mkdir ../../v0.11.13
nvm use 0.11.13
rmdir ../../v0.11.13

newLink="$(readlink ../../current)"

if [ "$(basename $newLink)" != 'v0.11.13' ];then
  echo "Expected 'current' to point to v0.11.13 but was $newLink"
  exit 1
fi
