#!/bin/sh

die () { echo $@ ; exit 1; }

. ../../../nvm.sh

NVM_TEST_VERSION=v0.10.7

# Remove the stuff we're clobbering.
[ -e ../../../$NVM_TEST_VERSION ] && rm -R ../../../$NVM_TEST_VERSION

# Install from binary
nvm install $NVM_TEST_VERSION || die "install $NVM_TEST_VERSION failed"

# Check
[ -d ../../../$NVM_TEST_VERSION ]
nvm run $NVM_TEST_VERSION --version | grep $NVM_TEST_VERSION || die "'nvm run $NVM_TEST_VERSION --version | grep $NVM_TEST_VERSION' failed"

