#!/bin/sh

set -e
. ../../nvm.sh

VERSION=v0.10.26

# Remove the stuff we're clobbering.
[ -e ../../$VERSION ] && rm -R ../../$VERSION

# Install from binary
nvm install $VERSION

# Check
[ -d ../../$VERSION ]
nvm run $VERSION --version | grep $VERSION
