#!/bin/sh

set -e
. ../../nvm.sh

# Remove the stuff we're clobbering.
[ -e ../../v0.10.25 ] && rm -R ../../v0.10.25
[ -e ../../v0.10.26 ] && rm -R ../../v0.10.26

# Install from binary
nvm install 0.10.25
nvm install 0.10.26

# Check
[ -d ../../v0.10.25 ]
[ -d ../../v0.10.26 ]

# Use the first one
nvm use 0.10.25

# Use the latest one
nvm use 0.10
node --version | grep v0.10.26
