#!/bin/sh

die () { echo "$@" ; rm -f .nvmrc; exit 1; }

\. ../../../nvm.sh

touch .testfornvmcat
echo 'test' > .testfornvmcat

OUTPUT=$(nvm cat -p -f .testfornvmcat -c || die 'nvm cat -p -f .testfornvmcat -c failed')
EXPECTED_OUTPUT="$(cat .testfornvmcat)"

[ "_$OUTPUT" = "_$EXPECTED_OUTPUT" ] \
  || die "'nvm cat -p -f .testfornvmcat -c' output was not as '${EXPECTED_OUTPUT}'; got '${OUTPUT}'"

rm -f .testfornvmcat
