#!/bin/sh

touch .testfornvmcat
rm -f .testfornvmcat
die() { echo "$@"; exit 1; }
nvm deactivate >/dev/null 2>&1

\. ../../../nvm.sh
OUTPUT=$(nvm cat -p -f .testfornvmcat -c 2> /dev/null && die nvm cat -p -f .testfornvmcat -c failed)
EXPECTED_OUTPUT=""

[ "_$OUTPUT" = "_$EXPECTED_OUTPUT" ] \
  || die "'nvm cat -p -f .testfornvmcat -c' output was not as '${EXPECTED_OUTPUT}'; got '${OUTPUT}'"
