#!/bin/sh

die () { echo "$@" ; rm -f .nvmrc; exit 1; }

\. ../../../nvm.sh

touch .nvmrc
echo '# test' > .nvmrc

OUTPUT=$(nvm cat -c || die 'nvm cat -c failed')
EXPECTED_OUTPUT="# test"

[ "_$OUTPUT" = "_$EXPECTED_OUTPUT" ] \
  || die "'nvm cat -c' output was not expected as '$EXPECTED_OUTPUT'; got '$OUTPUT'"

rm -f .nvmrc
