#!/bin/sh

die () { echo "$@" ; exit 1; }

\. ../../nvm.sh

# Remove the stuff we're clobbering.
[ -e "${NVM_DIR}/versions/io.js/v8.3.0" ] && rm -R "${NVM_DIR}/versions/io.js/v8.3.0"
[ -e "${NVM_DIR}/versions/io.js/v8.4.0" ] && rm -R "${NVM_DIR}/versions/io.js/v8.4.0"

# Install from binary
nvm install chakra-v8.3.0 || die "'nvm install chakra-v8.3.0' failed"
nvm i chakra-v8.4.0 || die "'nvm i chakra-v8.4.0' failed"

# Check
[ -d "${NVM_DIR}/versions/io.js/v8.3.0" ] || die "chakra v8.3.0 didn't exist"
[ -d "${NVM_DIR}/versions/io.js/v8.4.0" ] || die "chakra v8.4.0 didn't exist"

# Use the first one
nvm use chakra-8.3.0 || die "'nvm use chakra-8.3.0' failed"

# Use the latest one
nvm use chakra-8 || die "'nvm use chakra-8' failed"
[ "_$(node --version)" = "_v8.4.0" ] || die "'node --version' was not v8.4.0, got: $(node --version)"
