#!/bin/sh

die () { echo "$@" ; exit 1; }

export NVM_DIR="$(cd ../../.. && pwd)"

: nvm.sh
\. "${NVM_DIR}/nvm.sh"

# Create an alias file with trailing spaces and tabs
printf '22.1.0   \t \n' > ../../../alias/test-edge-trailing-ws
ACTUAL="$(nvm_alias test-edge-trailing-ws)"
EXPECTED='22.1.0'
[ "${ACTUAL}" = "${EXPECTED}" ] || die "expected >${EXPECTED}<, got >${ACTUAL}<"

rm -f ../../../alias/test-edge-trailing-ws
