#!/bin/sh

for i in $(seq 1 10)
  do
  rm -f "../../../alias/test-stable-$i"
  rm -rf "../../../v0.0.$i"
  rm -f "../../../alias/test-unstable-$i"
  rm -rf "../../../v0.1.$i"
  rm -rf "../../../alias/test-iojs-$i"
  rm -rf "../../../versions/io.js/v0.2.$i"
done

rm -f "../../../alias/stable"
rm -f "../../../alias/unstable"
rm -f "../../../alias/node"
rm -f "../../../alias/iojs"
rm -f "../../../alias/default"
rm -f "../../../alias/test-blank-lines"
rm -f "../../../alias/test-multi-lines"
rm -f "../../../alias/test-edge-"* "../../../alias/test edge spaces"
rm -f "../../../alias/self" "../../../alias/link1" "../../../alias/link2" "../../../alias/link3"
rm -f "../../../alias/foo bar" "../../../alias/midway" "../../../alias/bar"
rm -f "../../../alias/hop1" "../../../alias/hop2" "../../../alias/hop3" "../../../alias/hop4"
rm -f "../../../alias/axb" "../../../alias/a.b"
