#!/bin/sh

die () { echo "$@" ; exit 1; }

\. ../../../nvm.sh

\. ../../common.sh

nvm deactivate >/dev/null 2>&1 || die 'deactivate failed'

nvm_die_on_prefix() {
  echo >&2 "| $1 | $2 |"
  return 3
}

try nvm use --silent node
EXPECTED_OUTPUT=""
[ "_$CAPTURED_STDOUT" = "_$EXPECTED_OUTPUT" ] \
  || die "'nvm use --silent node' did not call through to 'nvm_die_on_prefix' and give output '$EXPECTED_OUTPUT'; got '$CAPTURED_STDOUT'"

try_err nvm use --silent node
EXPECTED_CODE="11"
[ "_$CAPTURED_EXIT_CODE" = "_$EXPECTED_CODE" ] \
  || die "'nvm use --silent node' when 'nvm_die_on_prefix' fails did not return '$EXPECTED_CODE'; got '$CAPTURED_EXIT_CODE'"
