#!/bin/sh

NVM_ENV=testing . ../../install.sh

safe_type() {
  type "$1" > /dev/null 2>&1 && return 0 || return 1
}

# Check nvm_reset exists
type nvm_reset > /dev/null 2>&1

# Apply nvm_reset
nvm_reset

# The names should be unset
! safe_type nvm_do_install && \
  ! safe_type nvm_has && \
  ! safe_type nvm_download && \
  ! safe_type install_nvm_as_script && \
  ! safe_type install_nvm_from_git && \
  ! safe_type nvm_reset
