#!/bin/sh

mkdir ../../../v0.1.3
mkdir ../../../v0.2.3
mkdir -p ../../../versions/node

. ../../../nvm.sh

[ -z "$(nvm ls | \grep 'versions')" ]
# The result should contain only the appropriate version numbers.

