#!/bin/sh

mkdir ../../../v0.1.3
mkdir ../../../v0.2.3

. ../../../nvm.sh

mkdir ../../../versions

[ -z "$(nvm ls | \grep 'versions')" ]
# The result should contain only the appropriate version numbers.

rmdir ../../../versions

