#!/bin/sh

\. ../../../nvm.sh

mkdir "${NVM_DIR}/v0.1.3"
mkdir "${NVM_DIR}/v0.2.3"
mkdir -p "${NVM_DIR}/versions/node"

[ -z "$(nvm ls | \grep 'versions')" ]
# The result should contain only the appropriate version numbers.
