#!/bin/sh

die () { echo $@ ; exit 1; }

mkdir -p ../../../versions/node/v0.12.1
mkdir ../../../v0.1.3

. ../../../nvm.sh

nvm ls 0.12 | grep v0.12.1 || die '"nvm ls" did not list a version in the versions/ directory'
nvm ls 0.1 | grep v0.1.3 || die '"nvm ls" did not list a version not in the versions/ directory'

