#!/bin/sh

set -ex

die () { echo "$@" ; exit 1; }

set +e # TODO: fix
\. ../../nvm.sh
set -e

nvm deactivate || die 'deactivate failed'

NVM_TEST_VERSION=v0.8.5

# Remove the stuff we're clobbering.
nvm uninstall "${NVM_TEST_VERSION}" || die 'uninstall failed'

# Install from source implicitly (v0.8.6 is when binaries started)
nvm install $NVM_TEST_VERSION || die "'nvm install -s $NVM_TEST_VERSION' failed"

# Check
[ -d ../../$NVM_TEST_VERSION ]
nvm run $NVM_TEST_VERSION --version | grep $NVM_TEST_VERSION || "'nvm run $NVM_TEST_VERSION --version | grep $NVM_TEST_VERSION' failed"

