#!/bin/sh

die () { echo "$@" ; exit 1; }

\. ../../common.sh

_returns_zero() { return 0; }
_returns_nonzero() { return 1; }

# assert_ok should pass for a zero-exit function
assert_ok _returns_zero \
  || die 'assert_ok failed on a function that returns 0'

# assert_ok should fail for a non-zero-exit function
if (assert_ok _returns_nonzero 2>/dev/null); then
  die 'assert_ok incorrectly passed for a function that returns 1'
fi
