#!/bin/sh

\. ../../../nvm.sh

cleanup () {
  rm -rf "${NVM_DIR}/v0.1.2/node"
}
die () { echo "$@" ; exit 1; }

mkdir "${NVM_DIR}/v0.1.2"
touch "${NVM_DIR}/v0.1.2/node"

nvm use 0.1.2

if command -v node; then
  nvm_has_system_node
else
  ! nvm_has_system_node
fi

nvm deactivate /dev/null 2>&1

if command -v node; then
  nvm_has_system_node
else
  ! nvm_has_system_node
fi
