#!/bin/sh

cleanup () {
  rm ../../../versions/io.js/v0.1.2/node
  rm ../../../versions/io.js/v0.1.2/iojs
  rmdir ../../../versions/io.js/v0.1.2
}
die () { echo $@ ; exit 1; }

. ../../../nvm.sh

mkdir ../../../versions/io.js/v0.1.2
touch ../../../versions/io.js/v0.1.2/node
touch ../../../versions/io.js/v0.1.2/iojs

nvm use iojs-v0.1.2

if command -v iojs; then
  nvm_has_system_iojs
else
  ! nvm_has_system_iojs
fi

nvm deactivate /dev/null 2>&1

if command -v iojs; then
  nvm_has_system_iojs
else
  ! nvm_has_system_iojs
fi

