#!/bin/sh

cleanup () {
  rm "${NVM_DIR}/versions/io.js/v0.1.2/node"
  rm "${NVM_DIR}/versions/io.js/v0.1.2/iojs"
  rmdir "${NVM_DIR}/versions/io.js/v0.1.2"
}
die () { echo "$@" ; exit 1; }

\. ../../../nvm.sh

mkdir "${NVM_DIR}/versions/io.js/v0.1.2"
touch "${NVM_DIR}/versions/io.js/v0.1.2/node"
touch "${NVM_DIR}/versions/io.js/v0.1.2/iojs"

nvm use iojs-v0.1.2

if command -v iojs; then
  nvm_has_system_iojs
else
  ! nvm_has_system_iojs
fi

nvm deactivate /dev/null 2>&1

if command -v iojs; then
  nvm_has_system_iojs
else
  ! nvm_has_system_iojs
fi
