#!/bin/sh

cleanup () {
  rm tmp/node
  rmdir tmp
  rm tmp2/node
  rmdir tmp2
}
die () { echo $@ ; cleanup; exit 1; }

. ../../../nvm.sh

mkdir -p tmp
touch tmp/node
mkdir -p tmp2
touch tmp2/node

nvm_tree_contains_path tmp tmp/node || die '"tmp" should contain "tmp/node"'

nvm_tree_contains_path tmp tmp2/node && die '"tmp" should not contain "tmp2/node"'

nvm_tree_contains_path tmp2 tmp2/node || die '"tmp2" should contain "tmp2/node"'

nvm_tree_contains_path tmp2 tmp/node && die '"tmp2" should not contain "tmp/node"'

cleanup

