#!/bin/sh

die () { echo "$@" ; exit 1; }

\. ../../../nvm.sh

x=0
i=0
runs=5
calls=500
first_result=false
if (nvm_supports_source_options && printf .); then
  first_result=true
fi
while [ $x -le $runs ]; do
  y=$x
  x=$(( x + 1 ))
  while [ $i -le $calls ]; do
    this_result=false
    if (nvm_supports_source_options && printf .); then
      this_result=true
    fi
    [ $this_result = $first_result ] || die "call ${i}, run ${y} got ${this_result}; expected ${first_result}"
    i=$(( i + 1 ))
  done
done
echo "${runs} runs of ${calls} calls succeeded"
