#!/bin/sh

cleanup () {
  unset -f die cleanup
  docker stop httpbin && docker rm httpbin
}
die () { echo "$@" ; cleanup ; exit 1; }

\. ../../../nvm.sh

set -ex

# nvm_download install.sh
nvm_download "https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/install.sh" >/dev/null || die "nvm_download unable to download install.sh"

# nvm_download should pass when calling with basic auth header with correct username and password
docker pull kennethreitz/httpbin && SHELL=bash docker run -d --name httpbin -p 80:80 kennethreitz/httpbin
sleep 1 # wait for httpbin to start
proxy="http://127.0.0.1/basic-auth/test/123%3F45%3E6"
NVM_AUTH_HEADER="Basic $(printf 'test:123?45>6' | base64)" nvm_download "${proxy}" > /dev/null || die 'nvm_download should pass when calling with basic auth header with correct username and password'

# nvm_download should fail when calling with basic auth header with incorrect password
NVM_AUTH_HEADER="Basic $(printf 'test:123?45>67' | base64)" nvm_download "${proxy}" > /dev/null && die 'nvm_download should fail when calling with basic auth header with incorrect password'

cleanup
