#!/bin/sh

die () { echo "$@" ; exit 1; }

: nvm.sh
\. ../../../nvm.sh
\. ../../common.sh

assert_not_ok nvm_iojs_version_has_solaris_binary ""
assert_not_ok nvm_iojs_version_has_solaris_binary "foo"
assert_not_ok nvm_iojs_version_has_solaris_binary "v1.1.0"

# Non-iojs versions should fail (version is unchanged after stripping iojs prefix)
assert_not_ok nvm_iojs_version_has_solaris_binary "v4.0.0"
assert_not_ok nvm_iojs_version_has_solaris_binary "v8.0.0"

# Bare versions without iojs- prefix are node versions, not iojs
assert_not_ok nvm_iojs_version_has_solaris_binary "v3.3.1"
assert_not_ok nvm_iojs_version_has_solaris_binary "v3.3.2"
assert_not_ok nvm_iojs_version_has_solaris_binary "v3.4.1"

assert_ok nvm_iojs_version_has_solaris_binary "iojs-v3.3.1"
assert_ok nvm_iojs_version_has_solaris_binary "iojs-v3.3.2"
assert_ok nvm_iojs_version_has_solaris_binary "iojs-v3.4.1"
